# make sure to replace "projectid" below with the project ID configured in the Google Developer Console
runtime: go
api_version: go1
# The vm setting is what determines if we are using a sandbox or MVM
vm: true
module: module1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.2

resources:
  cpu: .5
  memory_gb: 1.3

handlers:
- url: /.*
  script: _go_app
